FROM apache/airflow:3.0.2-python3.11

# Install Python packages needed for Airflow + DBT + S3
RUN pip install --no-cache-dir \
    "apache-airflow==${AIRFLOW_VERSION}" \
    dbt-core==1.8.7 \
    dbt-snowflake \
    apache-airflow-providers-amazon>==10.0.0 \
    boto3 \
    s3fs \
    dotenv==0.9.9 \
    pandas==2.1.4 \
    requests==2.32.3

USER root

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    libpq-dev \
    git \
    openjdk-17-jre-headless \
    wget \
    && rm -rf /var/lib/apt/lists/*

ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64

ENV AIRFLOW_HOME=/opt/airflow

USER airflow
