FROM python:3.9-slim

WORKDIR /app

# Install system dependencies for confluent-kafka
# (The python library requires librdkafka-dev)
RUN apt-get update && \
    apt-get install -y --no-install-recommends gcc libc-dev && \
    rm -rf /var/lib/apt/lists/*
    

# Install dependencies
RUN pip install --no-cache-dir \
    cassandra-driver==3.28.0 \
    confluent-kafka==2.1.1

# Copy the script
COPY sink_service.py .

# Command to run
CMD ["python", "-u", "sink_service.py"]